### ISSUE TITLE
finish the hackweek schedule

### ISSUE THREAD

**Issue by aaarendt** [geo-smart/2023-hackweek-website#11]
The geosmart schedule is in good shape, located [here](https://github.com/orgs/geo-smart/projects/2) as a github project page, but it's not ready to deploy because it's not formatted correctly. Right now all the cards representing tutorials are draft issues.

```[tasklist]
### Tasks needed
- [x] create a new repo in this geosmart org called "admin-issues" (just copy from the [ICESat-2 version?](https://github.com/ICESAT-2HackWeek/admin-issues))
- [x] recreate all the tutorial cards using the [issue tempate](https://github.com/geo-smart/2023-hackweek-admin-issues/blob/main/.github/ISSUE_TEMPLATE/hackweek-tutorial-scheduling-template.md)
- [x] ultimately we want everything to look like the [ICESat-2 schedule page](https://github.com/orgs/ICESAT-2HackWeek/projects/7) for ICESat-2.
- [ ] then we can run the [pyhackweek script](https://github.com/uwhackweek/pyhackweek) and make this year's schedule live
```

**Comment by jomey** [comment]
Created the admin issue repository based on the uwhackweek template
https://github.com/geo-smart/2023-hackweek-admin-issues

It also holds the template for issues to use as single schedule item (tutorial, break, ...).

**Comment by friedrichknuth** [comment]
Added [template information](https://github.com/geo-smart/2023-hackweek-admin-issues/blob/main/.github/ISSUE_TEMPLATE/hackweek-tutorial-scheduling-template.md) to [tutorial cards](https://github.com/orgs/geo-smart/projects/2/) and converted to [issues](https://github.com/geo-smart/2023-hackweek-admin-issues/issues).

**Comment by aaarendt** [comment]
Ran pyhackweek and we now have an initial draft:

https://github.com/geo-smart/2023-hackweek-website/pull/13
